services:
  # Django website service
  website:
    build:
      context: ./backend  # Build Django from the backend folder
      dockerfile: Dockerfile  # Dockerfile for Django backend
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      DEBUG: 'False'
      SECRET_KEY: ${SECRET_KEY}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
      AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME}
      AWS_QUERYSTRING_AUTH: ${AWS_QUERYSTRING_AUTH}
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - internal
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/staticfiles:/app/staticfiles:ro
      - certbot_certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - website
    restart: unless-stopped
    networks:
      - internal
      - external

  certbot-renew:
    image: certbot/certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
    command: renew --non-interactive --agree-tos

networks:
  internal:
  external:

volumes:
  certbot_certs:
  staticfiles:
