services:
  frontend-build:  # Build react if needed
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
    volumes:
      - ./backend/static/react_dist:/output
    command: sh -c "cp -r /app/dist/* /output/"

  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django website service
  website:
    build:
      context: ./backend  # Build Django from the backend folder
      dockerfile: Dockerfile  # Dockerfile for Django backend
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      STAGE: ${STAGE}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
      AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME}
      AWS_QUERYSTRING_AUTH: ${AWS_QUERYSTRING_AUTH}
    env_file:
      - .env
    volumes:
      - ./backend/static:/app/staticfiles
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      frontend-build:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.${STAGE}.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/static:/app/staticfiles:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - website
    restart: unless-stopped
    networks:
      - internal
      - external

  certbot-renew:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: renew --webroot -w /var/www/certbot --non-interactive --agree-tos

networks:
  internal:
  external:

volumes:
  certbot_www:
  staticfiles:
  postgres_data:
  react_build:
